// VuePage/src/views/index.vue
<template>
  <div class="opt-loader-demo">
    <div id="container" ref="containerRef"></div>

    <div class="left-nav" v-if="loaderReady">
      <div v-for="tool in tools" :key="tool.id" class="left-tool" :class="{ active: activeTool === tool.id }" @click="onToolClick(tool.id)">
        <img :src="getNavImage(tool.icon)" />
        <span>{{ tool.name }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, h, onMounted, onUnmounted } from "vue";
import { message, notification } from "ant-design-vue";
import {
  Scene,
  WebGLRenderer,
  PerspectiveCamera,
  AmbientLight,
  DirectionalLight,
  Color,
  Vector2,
} from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import OptRapid3dLoader from "../utils/OptRapid3dLoader";
import ColorPanel from "./panels/ColorPanel.vue";
import VisiblePanel from "./panels/VisiblePanel.vue";
import AlphaPanel from "./panels/AlphaPanel.vue";
import OffsetPanel from "./panels/OffsetPanel.vue";
import RotatePanel from "./panels/RotatePanel.vue";
import AttributePanel from "./panels/AttributePanel.vue";
import { useModelStore } from "../store/modules/model";
const containerRef = ref<HTMLDivElement | null>(null);
const loaderReady = ref(false);
const activeTool = ref("");

let loaderInstance: any = null;
let rendererInstance: WebGLRenderer | null = null;
let cameraInstance: PerspectiveCamera | null = null;
let controlsInstance: OrbitControls | null = null;
let animationId: number | null = null;

const tools = [
  { id: "attribute", name: "Properties", icon: "SubAttributes" },
  { id: "color", name: "Color", icon: "SubSetFeatureColor" },
  { id: "visible", name: "Visibility", icon: "SubHideOrShow" },
  { id: "alpha", name: "Opacity", icon: "ComponentTransparency" },
  { id: "offset", name: "Offset", icon: "SubFeatureOffset" },
  { id: "rotate", name: "Rotate", icon: "SubSetFeatureRotate" },
  { id: "website", name: "Website", icon: "home" },
  // { id: "download", name: "Source Download", icon: "Export" },
];

function getNavImage(name: string) {
  return new URL(`../assets/img/${name}.png`, import.meta.url).href;
}

function onToolClick(id: string) {
  if (id === "website") {
    window.open("https://www.opt3ds.com", "_blank");
    return;
  }
  if (id === "download") {
    const link = document.createElement("a");
    link.href = "./static/Opt Rapid3D Loader for Three.js.zip";
    link.download = "Opt Rapid3D Loader for Three.js.zip";
    link.click();
    return;
  }
  if (activeTool.value === id) {
    activeTool.value = "";
    notification.destroy();
    return;
  }
  activeTool.value = id;
  notification.destroy();

  const panelMap: Record<string, any> = {
    attribute: AttributePanel,
    color: ColorPanel,
    visible: VisiblePanel,
    alpha: AlphaPanel,
    offset: OffsetPanel,
    rotate: RotatePanel,
  };

  const titleMap: Record<string, string> = {
    attribute: "Properties",
    color: "Color",
    visible: "Visibility",
    alpha: "Opacity",
    offset: "Offset",
    rotate: "Rotate",
  };

  const PanelComponent = panelMap[id];
  if (PanelComponent && rendererInstance) {
    notification.open({
      key: "EngineKey",
      message: titleMap[id],
      description: () =>
        h(PanelComponent, {
          loader: loaderInstance,
          canvas: rendererInstance!.domElement,
        }),
      class: "engine-notification",
      duration: null,
      placement: "topRight",
      style: { width: "300px", marginRight: "20px" },
      onClose: () => {
        activeTool.value = "";
      },
    });
  }
}

function onResize() {
  if (!cameraInstance || !rendererInstance) return;
  cameraInstance.aspect = window.innerWidth / window.innerHeight;
  cameraInstance.updateProjectionMatrix();
  rendererInstance.setSize(window.innerWidth, window.innerHeight);
}

onMounted(async () => {
  try {
    const scene = new Scene();
    scene.background = new Color(0x87cefa);
    const renderer = new WebGLRenderer({
      antialias: true,
      logarithmicDepthBuffer: true,
    });
    renderer.setSize(window.innerWidth, window.innerHeight);
    rendererInstance = renderer;
    if (containerRef.value) {
      containerRef.value.appendChild(renderer.domElement);
    }
    const camera = new PerspectiveCamera(
      60,
      window.innerWidth / window.innerHeight,
      0.1,
      1000
    );
    camera.position.set(0, 100, 150);
    camera.lookAt(0, 0, 0);
    cameraInstance = camera;
    const controls = new OrbitControls(camera, renderer.domElement);
    controls.enableDamping = true;
    controls.dampingFactor = 0.05;
    controlsInstance = controls;
    const ambientLight = new AmbientLight(0xffffff, 2.0);
    scene.add(ambientLight);
    const mainLight = new DirectionalLight(0xffffff, 1.0);
    mainLight.position.set(5, 10, 7);
    scene.add(mainLight);
    const store = useModelStore();
    const baseUrl = store.baseUrl || "";
    const loader = new OptRapid3dLoader({
      renderer: renderer,
      camera: camera,
      parent: scene,
      doubleSide: true,
      libs: "./static/libs",
      url: baseUrl + `/static/OutputModel/${store.modelName}/root.opt`,
      callback: () => {
        console.log("Loading completed!");
        loaderReady.value = true;
      },
    });
    window.api = loader
    loaderInstance = loader;
    window.addEventListener("resize", onResize);
    function animate() {
      animationId = requestAnimationFrame(animate);
      controls.update();
      loader.interface.update();
      renderer.render(scene, camera);
    }
    animate();
  } catch (error) {
    console.error("Initialization failed:", error);
    message.error("Initialization failed, please refresh the page and try again");
  }
});

onUnmounted(() => {
  if (animationId !== null) cancelAnimationFrame(animationId);
  notification.destroy();
  if (rendererInstance) rendererInstance.dispose();
  if (controlsInstance) controlsInstance.dispose();
  window.removeEventListener("resize", onResize);
});
</script>

<style lang="less" scoped>
.opt-loader-demo {
  width: 100vw;
  height: 100vh;
  position: relative;
  overflow: hidden;
}

#container {
  width: 100%;
  height: 100%;
}

@keyframes glow-pulse {
  0%,
  100% {
    box-shadow: 0 0 8px rgba(22, 119, 255, 0.4);
  }
  50% {
    box-shadow: 0 0 20px rgba(64, 150, 255, 0.7);
  }
}

.left-nav {
  position: fixed;
  left: 0;
  top: 50%;
  transform: translateY(-50%);
  display: flex;
  flex-direction: column;
  z-index: 100;
  background: rgba(50, 54, 65, 0.88);
  border-top-right-radius: 8px;
  border-bottom-right-radius: 8px;
  overflow: hidden;

  .left-tool {
    padding: 10px 0;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    font-size: 12px;
    color: rgba(255, 255, 255, 0.7);
    cursor: pointer;
    transition: all 0.3s ease;
    width: 60px;

    img {
      width: 24px;
      height: 24px;
      margin-bottom: 6px;
      transition: all 0.3s ease;
    }

    span {
      white-space: nowrap;
      letter-spacing: 0.5px;
    }

    &:hover {
      background: rgba(22, 119, 255, 0.5);
      color: #fff;

      img {
        filter: drop-shadow(0 0 4px rgba(22, 119, 255, 0.5));
      }
    }

    &.active {
      background: rgba(22, 119, 255, 0.75);
      color: #fff;
      animation: glow-pulse 2.5s ease-in-out infinite;

      img {
        filter: drop-shadow(0 0 6px rgba(22, 119, 255, 0.6));
      }
    }
  }
}

.tips-bar {
  position: fixed;
  bottom: 20px;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
  gap: 30px;
  background: rgba(50, 54, 65, 0.9);
  padding: 12px 25px;
  border-radius: 8px;
  z-index: 100;

  .tip-item {
    display: flex;
    align-items: center;
    color: rgba(255, 255, 255, 0.65);
    font-size: 13px;

    img {
      width: 24px;
      height: 24px;
      margin-right: 8px;
    }
  }
}
</style>

// ReactPage/src/views/Index.tsx
/**
 * Main page component
 * Responsibilities:
 * 1. Initialize the Three.js scene, camera, renderer, orbit controls, and lights
 * 2. Load the lightweight model via OptRapid3dLoader and show the left toolbar after loading completes
 * 3. Manage the left toolbar click logic, popping up the corresponding function panel on the right via antd notification
 * 4. Listen for window resize to keep the canvas adaptive to full screen
 */
import React, { useEffect, useRef, useState } from "react";
import { notification } from "antd";
import {
  Scene,
  WebGLRenderer,
  PerspectiveCamera,
  AmbientLight,
  DirectionalLight,
  Color,
} from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import OptRapid3dLoader from "../utils/OptRapid3dLoader";
import { getModelMessage } from "../config";
import AttributePanel from "./panels/AttributePanel";
import ColorPanel from "./panels/ColorPanel";
import VisiblePanel from "./panels/VisiblePanel";
import AlphaPanel from "./panels/AlphaPanel";
import OffsetPanel from "./panels/OffsetPanel";
import RotatePanel from "./panels/RotatePanel";
import SubAttributesIcon from "../assets/img/SubAttributes.png";
import SubSetFeatureColorIcon from "../assets/img/SubSetFeatureColor.png";
import SubHideOrShowIcon from "../assets/img/SubHideOrShow.png";
import ComponentTransparencyIcon from "../assets/img/ComponentTransparency.png";
import SubFeatureOffsetIcon from "../assets/img/SubFeatureOffset.png";
import SubSetFeatureRotateIcon from "../assets/img/SubSetFeatureRotate.png";
import HomeIcon from "../assets/img/home.png";

// Toolbar definition fully consistent with index.vue
const tools = [
  { id: "attribute", name: "Properties", icon: SubAttributesIcon },
  { id: "color", name: "Color", icon: SubSetFeatureColorIcon },
  { id: "visible", name: "Visibility", icon: SubHideOrShowIcon },
  { id: "alpha", name: "Opacity", icon: ComponentTransparencyIcon },
  { id: "offset", name: "Offset", icon: SubFeatureOffsetIcon },
  { id: "rotate", name: "Rotate", icon: SubSetFeatureRotateIcon },
  { id: "website", name: "Website", icon: HomeIcon },
];

interface PanelProps {
  loader: any;
  canvas: HTMLCanvasElement;
}

const panelMap: Record<string, React.ComponentType<PanelProps>> = {
  attribute: AttributePanel,
  color: ColorPanel,
  visible: VisiblePanel,
  alpha: AlphaPanel,
  offset: OffsetPanel,
  rotate: RotatePanel,
};

const titleMap: Record<string, string> = {
  attribute: "Properties",
  color: "Color",
  visible: "Visibility",
  alpha: "Opacity",
  offset: "Offset",
  rotate: "Rotate",
};

export default function Index() {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const loaderRef = useRef<any>(null);
  const [loaderReady, setLoaderReady] = useState(false);
  const [activeTool, setActiveTool] = useState("");
  const onToolClickRef = useRef<(id: string) => void>(() => {});

  // Root cause fix: the holder of the antd v5 static notification is rendered through the react-dom main entry
  // (unstableSetRender -> rc-util render). The main entry of React 19 no longer exports
  // createRoot / render, so the fragment is never mounted and the panel never appears.
  // Switched to the hook version API: the holder is rendered as a regular node into the main React tree,
  // and api.open / api.destroy(key) semantics match the static version (replace / close with the same key).
  const [notify, notifyHolder] = notification.useNotification();

  useEffect(() => {
    let scene: Scene | null = null;
    let renderer: WebGLRenderer | null = null;
    let camera: PerspectiveCamera | null = null;
    let controls: OrbitControls | null = null;
    let loader: any = null;
    let animationId = 0;

    function onResize() {
      if (!camera || !renderer) return;
      camera.aspect = window.innerWidth / window.innerHeight;
      camera.updateProjectionMatrix();
      renderer.setSize(window.innerWidth, window.innerHeight);
    }

    try {
      scene = new Scene();
      scene.background = new Color(0x87cefa);
      renderer = new WebGLRenderer({
        antialias: true,
        logarithmicDepthBuffer: true,
      });
      renderer.setSize(window.innerWidth, window.innerHeight);
      if (containerRef.current) {
        containerRef.current.appendChild(renderer.domElement);
      }
      canvasRef.current = renderer.domElement;
      camera = new PerspectiveCamera(
        60,
        window.innerWidth / window.innerHeight,
        0.1,
        1000
      );
      camera.position.set(0, 100, 150);
      camera.lookAt(0, 0, 0);
      controls = new OrbitControls(camera, renderer.domElement);
      controls.enableDamping = true;
      controls.dampingFactor = 0.05;
      const ambientLight = new AmbientLight(0xffffff, 2.0);
      scene.add(ambientLight);
      const mainLight = new DirectionalLight(0xffffff, 1.0);
      mainLight.position.set(5, 10, 7);
      scene.add(mainLight);

      const { baseUrl, modelName } = getModelMessage();
      loader = new OptRapid3dLoader({
        renderer: renderer,
        camera: camera,
        parent: scene,
        doubleSide: true,
        libs: "./static/libs",
        url: `${baseUrl}/static/OutputModel/${modelName}/root.opt`,
        callback: () => {
          console.log("Loading completed!");
          setLoaderReady(true);
        },
      });
      (window as any).api = loader;
      loaderRef.current = loader;

      window.addEventListener("resize", onResize);

      function animate() {
        animationId = requestAnimationFrame(animate);
        if (controls) controls.update();
        if (loader) loader.interface.update();
        if (scene && camera && renderer) renderer.render(scene, camera);
      }
      animate();
    } catch (error) {
      console.error("Initialization failed:", error);
      notify.error({
        message: "Initialization failed",
        description: "Initialization failed, please refresh the page and try again",
        duration: 6,
      });
    }

    // Clean up Three.js related resources when the component unmounts to avoid memory leaks
    return () => {
      if (animationId !== 0) cancelAnimationFrame(animationId);
      window.removeEventListener("resize", onResize);
      try {
        if (loader && loader.interface && loader.interface.dispose) {
          loader.interface.dispose();
        }
      } catch (e) {
        console.error("loader dispose failed:", e);
      }
      if (controls) controls.dispose();
      if (renderer) renderer.dispose();
    };
    // notify is the stable api returned by notification.useNotification(),
    // so referencing it in the effect is safe (unrelated to the component lifecycle).
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  /**
   * Left toolbar click handler
   * - website: jump to the official website
   * - Clicking an already activated tool again: close the panel
   * - Other tools: close the old panel and open the new one; when closing, also clear the activeTool highlight
   */
  function onToolClick(id: string) {
    if (id === "website") {
      window.open("https://www.opt3ds.com", "_blank");
      return;
    }
    if (activeTool === id) {
      setActiveTool("");
      notify.destroy("EngineKey");
      return;
    }
    setActiveTool(id);
    notify.destroy("EngineKey");

    const PanelComponent = panelMap[id];
    if (PanelComponent && canvasRef.current) {
      notify.open({
        key: "EngineKey",
        message: titleMap[id],
        description: (
          <PanelComponent loader={loaderRef.current} canvas={canvasRef.current} />
        ),
        className: "engine-notification",
        duration: null,
        placement: "topRight",
        style: { width: "300px", marginRight: "20px" },
        onClose: () => {
          setActiveTool("");
        },
      });
    }
  }

  onToolClickRef.current = onToolClick;

  return (
    <div className="opt-loader-demo">
      {notifyHolder}
      <div id="container" ref={containerRef} />
      {loaderReady && (
        <div className="left-nav">
          {tools.map((tool) => (
            <div
              key={tool.id}
              className={`left-tool${activeTool === tool.id ? " active" : ""}`}
              onClick={() => onToolClick(tool.id)}
            >
              <img src={tool.icon} />
              <span>{tool.name}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
