// src/views/panels/AlphaPanel.vue
<template>
  <div class="side-frame" @contextmenu.prevent="" ref="wrap">
    <a-space class="operate-btn-box">
      <a-button ghost @click="DeleteAll">Delete All</a-button>
    </a-space>
    <a-card size="small" :bordered="false" :body-style="{ padding: 0 }">
      <div class="box">
        <a-list
          size="small"
          :data-source="componentList"
          :locale="{ emptyText: `No history` }"
          class="roam-list scroll-box"
        >
          <template #renderItem="{ item, index }">
            <a-list-item>
              <a-space>
                <div>{{ item.id }}</div>
              </a-space>
              <template #actions>
                <a-tooltip title="Delete">
                  <DeleteOutlined :style="{ fontSize: '16px', color: '#05a081' }" @click="onDelete(item, index)" />
                </a-tooltip>
              </template>
            </a-list-item>
          </template>
        </a-list>
      </div>
    </a-card>
    <Modal
      class="set-data"
      :visible="visible"
      @ok="confirmChange"
      @cancel="handleCancel"
      title="Set Component Opacity"
      ok-text="OK"
      cancel-text="Cancel"
      :width="320"
      :maskClosable="false"
      :mask="false"
      :centered="true"
      :getContainer="() => $refs.wrap"
    >
      <a-form>
        <a-form-item label="Opacity" :label-col="{ span: 6 }" :wrapper-col="{ span: 18 }">
          <a-input-number v-model:value="inputValue" :step="0.1" :min="0" :max="1" />
        </a-form-item>
      </a-form>
    </Modal>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from "vue";
import { message } from "ant-design-vue";
import { DeleteOutlined } from "@ant-design/icons-vue";
import { Vector2 } from "three";
import Modal from "../../components/Modal.vue";

const props = defineProps<{
  loader: any;
  canvas: HTMLCanvasElement;
}>();

const componentList = ref<Array<{}>>([]);
const visible = ref(false);
const inputValue = ref(0.5);
const featureId = ref<any>(undefined);

async function onCanvasClick(event: MouseEvent) {
  const rect = props.canvas.getBoundingClientRect();
  const x = event.clientX - rect.left;
  const y = event.clientY - rect.top;
  try {
    const json = await props.loader.interface.pick({ position: new Vector2(x, y) });
    if (json != undefined) {
      console.log("Component ID", json.id);
      featureId.value = json.id;
      visible.value = true;
    }
  } catch (e) {
    console.error(e);
  }
}

async function onDelete(data: any, index: number) {
  componentList.value.splice(index, 1);
  await props.loader.interface.setAlpha({
    featureIds: data.id,
    alpha: 1,
  });
}

async function confirmChange() {
  await props.loader.interface.setAlpha({
    featureIds: featureId.value,
    alpha: inputValue.value,
  });
  let haveList = componentList.value.findIndex((item: any) => item.id == featureId.value);
  haveList == -1
    ? componentList.value.push({
        id: featureId.value,
        transparent: inputValue.value,
      })
    : ((componentList.value[haveList] as any).transparent = inputValue.value);
  visible.value = false;
}

function handleCancel() {
  visible.value = false;
}

async function DeleteAll() {
  for (const item of componentList.value) {
    await props.loader.interface.setAlpha({
      featureIds: (item as any).id,
      alpha: 1,
    });
  }
  componentList.value = [];
}

onMounted(() => {
  message.open({
    content: "Click to pick a component",
    duration: 2,
  });
  props.canvas.addEventListener("click", onCanvasClick);
});

onBeforeUnmount(() => {
  DeleteAll();
  props.canvas.removeEventListener("click", onCanvasClick);
});
</script>

<style scoped lang="less"></style>

// ReactPage/src/views/panels/AlphaPanel.tsx
/**
 * Feature transparency panel
 * - After picking a feature, a transparency setting dialog pops up
 * - After being applied, the feature is rendered with the specified transparency and recorded in the history list
 * - When deleted or unmounted, full opacity is restored (alpha = 1)
 */
import React, { useEffect, useRef, useState } from "react";
import { App, Space, Button, Card, List, Tooltip, Form, InputNumber } from "antd";
import { DeleteOutlined } from "@ant-design/icons";
import { Vector2 } from "three";
import DraggableModal from "../../components/DraggableModal";
import { useCanvasPick } from "./useCanvasPick";

interface AlphaItem {
  id: string;
  transparent: number;
}

export default function AlphaPanel(props: { loader: any; canvas: HTMLCanvasElement }) {
  const { loader, canvas } = props;
  const { message } = App.useApp();
  const [transparent, setTransparent] = useState<number>(0.5);
  const [componentList, setComponentList] = useState<AlphaItem[]>([]);
  const [visible, setVisible] = useState(false);
  const [featureId, setFeatureId] = useState<string | undefined>(undefined);
  const listRef = useRef(componentList);
  listRef.current = componentList;

  useEffect(() => {
    message.open({ content: "Please click to pick a feature", duration: 2 });
  }, []);

  /** Open the transparency setting dialog after picking a feature */
  async function onCanvasClick(event: MouseEvent) {
    const rect = canvas.getBoundingClientRect();
    const x = event.clientX - rect.left;
    const y = event.clientY - rect.top;

    try {
      const json = await loader.interface.pick({ position: new Vector2(x, y) });
      if (json != undefined) {
        setFeatureId(json.id);
        setVisible(true);
      }
    } catch (e) {
      console.error(e);
    }
  }

  function onDelete(data: AlphaItem, index: number) {
    setComponentList((list) => list.filter((_, i) => i !== index));
    loader.interface.setAlpha({ featureIds: data.id, alpha: 1 });
  }

  /** After confirming the transparency, apply it to the current feature and add it to the history list */
  async function SaveFeatureAlpha() {
    await loader.interface.setAlpha({
      featureIds: featureId,
      alpha: transparent,
    });
    setComponentList((list) => {
      const idx = list.findIndex((item) => item.id == featureId);
      if (idx === -1) {
        return [...list, { id: featureId!, transparent }];
      }
      return list.map((item, i) => (i === idx ? { ...item, transparent } : item));
    });
    setVisible(false);
  }

  /** Clear the history list and restore all features to full opacity */
  function DeleteAll() {
    listRef.current.forEach((item) => {
      loader.interface.setAlpha({ featureIds: item.id, alpha: 1 });
    });
    setComponentList([]);
  }

  useCanvasPick(canvas, onCanvasClick, () => {
    listRef.current.forEach((item) => {
      loader.interface.setAlpha({ featureIds: item.id, alpha: 1 });
    });
  });

  return (
    <div className="side-frame" onContextMenu={(e) => e.preventDefault()}>
      <Space className="operate-btn-box">
        <Button ghost onClick={DeleteAll}>
          Delete All
        </Button>
      </Space>

      <Card size="small" bordered={false} styles={{ body: { padding: 0 } }}>
        <div className="box">
          <List
            size="small"
            dataSource={componentList}
            locale={{ emptyText: "No history data" }}
            className="roam-list scroll-box"
          >
            {componentList.map((item, index) => (
              <List.Item
                key={item.id}
                actions={[
                  <Tooltip title="Delete" key="del">
                    <DeleteOutlined
                      style={{ fontSize: "16px", color: "#05a081" }}
                      onClick={() => onDelete(item, index)}
                    />
                  </Tooltip>,
                ]}
              >
                <Space>
                  <div>{item.id}</div>
                </Space>
              </List.Item>
            ))}
          </List>
        </div>
      </Card>

      <DraggableModal
        open={visible}
        className="set-data"
        title="Set Feature Transparency"
        okText="OK"
        cancelText="Cancel"
        width={320}
        onOk={SaveFeatureAlpha}
        onCancel={() => setVisible(false)}
      >
        <Form>
          <Form.Item
            label="Transparency"
            labelCol={{ span: 6 }}
            wrapperCol={{ span: 18 }}
            className="transparent"
          >
            <InputNumber
              step={0.1}
              min={0}
              max={1}
              value={transparent}
              onChange={(v) => setTransparent(v ?? 1)}
            />
          </Form.Item>
        </Form>
      </DraggableModal>
    </div>
  );
}
